spring:
  datasource:
    driver-class-name: com.mysql.jdbc.Driver
    url: jdbc:mysql://127.0.0.1:3307/carcircle?serverTimezone=UTC&useUnicode=true&characterEncoding=utf-8&zeroDateTimeBehavior=convertToNull&useSSL=false&allowPublicKeyRetrieval=true
    username: root
    password: lll136589
#  security:
#    user:
#      name: user
#      password: 111111
  redis:
    database: 0
    host: 127.0.0.1
    port: 6379
    password: lll136589
mybatis-pluse:
    mapper-locations: classpath*:/mapper/*Mapper.xml
    type-aliases-package: com.circlett.pojo
    global-config:
      logic-ont-delete-value: 1
      logic-delete-value: 0
server:
    port: 8082
circle:
    jwt:
     expire: 604800 #7天，秒单位
     secret: ji8n3439n439n43ld9ne9343fdfer49h
     header: Authorization
#服务器图片上传映射地址
uploadPathImg: /root/lsz/
#  /root/lsz/
#服务器的IP地址
ip: 121.4.90.69
     

